UK:
  keywords: [United Kingdom, England]  # not politically correct
  base: https://metdatasa.blob.core.windows.net/covid19-response/shapefiles/England
  name: Counties_and_Unitary_Authorities_April_2019_Boundaries_EW_BUC
  from_geopandas_args:
    names: ctyua19nm
    abbrevs: ctyua19cd