name: covid19-dev
channels:
  - conda-forge
  - anaconda
dependencies:
  - pangeo-notebook # contains dask, distributed, jupyter
  - xarray
  - intake-xarray
  - nb_black
  - pip
  - gcsfs
  - zarr
  - intake
  - cftime
  - iris
  - pandas
  # vis
  - bokeh
  - matplotlib
  - cartopy # mapping
  - h5netcdf
  - pip:
    - git+https://github.com/mathause/regionmask.git
    - azure-storage-blob
